/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file osal_err_values.h
 * @brief Shared numeric values for osal_err_t (identical on ESP-IDF and POSIX).
 */

#pragma once

/* Core (aligned with esp_err_t on ESP-IDF for 0x101-0x107) */
#define OSAL_ERR_VAL_FAIL                   (-1)
#define OSAL_ERR_VAL_OK                     (0)
#define OSAL_ERR_VAL_NO_MEM                 0x101
#define OSAL_ERR_VAL_INVALID_ARG            0x102
#define OSAL_ERR_VAL_INVALID_STATE          0x103
#define OSAL_ERR_VAL_TIMEOUT                0x104
#define OSAL_ERR_VAL_NOT_FOUND              0x105
#define OSAL_ERR_VAL_NOT_SUPPORTED          0x106
#define OSAL_ERR_VAL_INVALID_RESPONSE       0x107

/* HTTP (0xD001-0xD00F) */
#define OSAL_ERR_VAL_HTTP_CONNECTION_FAILED 0xD001

/* MQTT (0xD010-0xD01F) */
#define OSAL_ERR_VAL_MQTT_SEND_FAILED       0xD010
#define OSAL_ERR_VAL_MQTT_RECV_FAILED       0xD011
#define OSAL_ERR_VAL_MQTT_BAD_RESPONSE      0xD012
#define OSAL_ERR_VAL_MQTT_SERVER_REFUSED    0xD013
#define OSAL_ERR_VAL_MQTT_NO_DATA_AVAILABLE 0xD014
#define OSAL_ERR_VAL_MQTT_STATE_COLLISION   0xD015
#define OSAL_ERR_VAL_MQTT_KEEP_ALIVE_TIMEOUT 0xD016
#define OSAL_ERR_VAL_MQTT_NEED_MORE_BYTES   0xD017
#define OSAL_ERR_VAL_MQTT_NOT_CONNECTED     0xD018

/* NVS (0xD020-0xD027) */
#define OSAL_ERR_VAL_NVS_NOT_INITIALIZED    0xD020
#define OSAL_ERR_VAL_NVS_PARTITION_NOT_FOUND 0xD021
#define OSAL_ERR_VAL_NVS_NAMESPACE_NOT_FOUND 0xD022
#define OSAL_ERR_VAL_NVS_KEY_NOT_FOUND      0xD023

/* OTA (0xD030-0xD03F) */
#define OSAL_ERR_VAL_OTA_INVALID_SIZE       0xD030
#define OSAL_ERR_VAL_OTA_PARTITION_CONFLICT 0xD031
#define OSAL_ERR_VAL_OTA_SELECT_INFO_INVALID 0xD032
#define OSAL_ERR_VAL_OTA_VALIDATE_FAILED    0xD033
#define OSAL_ERR_VAL_OTA_SMALL_SEC_VER      0xD034
#define OSAL_ERR_VAL_OTA_ROLLBACK_FAILED    0xD035
#define OSAL_ERR_VAL_OTA_ROLLBACK_INVALID_STATE 0xD036

/* RainMaker / product extension (same numeric space as ESP_ERR_RMAKER_BASE) */
#ifndef OSAL_ERR_VAL_RMAKER_BASE
#define OSAL_ERR_VAL_RMAKER_BASE            0x7000
#endif
#define OSAL_ERR_VAL_RMAKER_NOT_INITIALIZED     (OSAL_ERR_VAL_RMAKER_BASE + 0)
#define OSAL_ERR_VAL_RMAKER_ALREADY_INITIALIZED (OSAL_ERR_VAL_RMAKER_BASE + 1)
#define OSAL_ERR_VAL_RMAKER_NOT_CONNECTED       (OSAL_ERR_VAL_RMAKER_BASE + 2)
#define OSAL_ERR_VAL_RMAKER_ALREADY_CONNECTED   (OSAL_ERR_VAL_RMAKER_BASE + 3)
#define OSAL_ERR_VAL_RMAKER_NOT_DISCONNECTED    (OSAL_ERR_VAL_RMAKER_BASE + 4)
#define OSAL_ERR_VAL_RMAKER_ALREADY_EXISTS      (OSAL_ERR_VAL_RMAKER_BASE + 5)
