/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: local_ctrl.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "local_ctrl/pb-c.h"
void   rmaker_local_ctrl__payload_buf__init
                     (RmakerLocalCtrl__PayloadBuf         *message)
{
  static const RmakerLocalCtrl__PayloadBuf init_value = RMAKER_LOCAL_CTRL__PAYLOAD_BUF__INIT;
  *message = init_value;
}
size_t rmaker_local_ctrl__payload_buf__get_packed_size
                     (const RmakerLocalCtrl__PayloadBuf *message)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__payload_buf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmaker_local_ctrl__payload_buf__pack
                     (const RmakerLocalCtrl__PayloadBuf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__payload_buf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmaker_local_ctrl__payload_buf__pack_to_buffer
                     (const RmakerLocalCtrl__PayloadBuf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__payload_buf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmakerLocalCtrl__PayloadBuf *
       rmaker_local_ctrl__payload_buf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmakerLocalCtrl__PayloadBuf *)
     protobuf_c_message_unpack (&rmaker_local_ctrl__payload_buf__descriptor,
                                allocator, len, data);
}
void   rmaker_local_ctrl__payload_buf__free_unpacked
                     (RmakerLocalCtrl__PayloadBuf *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rmaker_local_ctrl__payload_buf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmaker_local_ctrl__cmd_get_data__init
                     (RmakerLocalCtrl__CmdGetData         *message)
{
  static const RmakerLocalCtrl__CmdGetData init_value = RMAKER_LOCAL_CTRL__CMD_GET_DATA__INIT;
  *message = init_value;
}
size_t rmaker_local_ctrl__cmd_get_data__get_packed_size
                     (const RmakerLocalCtrl__CmdGetData *message)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__cmd_get_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmaker_local_ctrl__cmd_get_data__pack
                     (const RmakerLocalCtrl__CmdGetData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__cmd_get_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmaker_local_ctrl__cmd_get_data__pack_to_buffer
                     (const RmakerLocalCtrl__CmdGetData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__cmd_get_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmakerLocalCtrl__CmdGetData *
       rmaker_local_ctrl__cmd_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmakerLocalCtrl__CmdGetData *)
     protobuf_c_message_unpack (&rmaker_local_ctrl__cmd_get_data__descriptor,
                                allocator, len, data);
}
void   rmaker_local_ctrl__cmd_get_data__free_unpacked
                     (RmakerLocalCtrl__CmdGetData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rmaker_local_ctrl__cmd_get_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmaker_local_ctrl__resp_get_data__init
                     (RmakerLocalCtrl__RespGetData         *message)
{
  static const RmakerLocalCtrl__RespGetData init_value = RMAKER_LOCAL_CTRL__RESP_GET_DATA__INIT;
  *message = init_value;
}
size_t rmaker_local_ctrl__resp_get_data__get_packed_size
                     (const RmakerLocalCtrl__RespGetData *message)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__resp_get_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmaker_local_ctrl__resp_get_data__pack
                     (const RmakerLocalCtrl__RespGetData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__resp_get_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmaker_local_ctrl__resp_get_data__pack_to_buffer
                     (const RmakerLocalCtrl__RespGetData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__resp_get_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmakerLocalCtrl__RespGetData *
       rmaker_local_ctrl__resp_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmakerLocalCtrl__RespGetData *)
     protobuf_c_message_unpack (&rmaker_local_ctrl__resp_get_data__descriptor,
                                allocator, len, data);
}
void   rmaker_local_ctrl__resp_get_data__free_unpacked
                     (RmakerLocalCtrl__RespGetData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rmaker_local_ctrl__resp_get_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmaker_local_ctrl__rmaker_local_ctrl_payload__init
                     (RmakerLocalCtrl__RMakerLocalCtrlPayload         *message)
{
  static const RmakerLocalCtrl__RMakerLocalCtrlPayload init_value = RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__INIT;
  *message = init_value;
}
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__get_packed_size
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload *message)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__pack
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__pack_to_buffer
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmakerLocalCtrl__RMakerLocalCtrlPayload *
       rmaker_local_ctrl__rmaker_local_ctrl_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmakerLocalCtrl__RMakerLocalCtrlPayload *)
     protobuf_c_message_unpack (&rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor,
                                allocator, len, data);
}
void   rmaker_local_ctrl__rmaker_local_ctrl_payload__free_unpacked
                     (RmakerLocalCtrl__RMakerLocalCtrlPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rmaker_local_ctrl__payload_buf__field_descriptors[3] =
{
  {
    "Offset",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__PayloadBuf, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__PayloadBuf, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TotalLen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__PayloadBuf, totallen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmaker_local_ctrl__payload_buf__field_indices_by_name[] = {
  0,   /* field[0] = Offset */
  1,   /* field[1] = Payload */
  2,   /* field[2] = TotalLen */
};
static const ProtobufCIntRange rmaker_local_ctrl__payload_buf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rmaker_local_ctrl__payload_buf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.PayloadBuf",
  "PayloadBuf",
  "RmakerLocalCtrl__PayloadBuf",
  "rmaker_local_ctrl",
  sizeof(RmakerLocalCtrl__PayloadBuf),
  3,
  rmaker_local_ctrl__payload_buf__field_descriptors,
  rmaker_local_ctrl__payload_buf__field_indices_by_name,
  1,  rmaker_local_ctrl__payload_buf__number_ranges,
  (ProtobufCMessageInit) rmaker_local_ctrl__payload_buf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rmaker_local_ctrl__cmd_get_data__field_descriptors[4] =
{
  {
    "DataType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__CmdGetData, datatype),
    &rmaker_local_ctrl__rmaker_local_ctrl_data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__CmdGetData, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__CmdGetData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HasTimestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__CmdGetData, hastimestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmaker_local_ctrl__cmd_get_data__field_indices_by_name[] = {
  0,   /* field[0] = DataType */
  3,   /* field[3] = HasTimestamp */
  1,   /* field[1] = Offset */
  2,   /* field[2] = Timestamp */
};
static const ProtobufCIntRange rmaker_local_ctrl__cmd_get_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rmaker_local_ctrl__cmd_get_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.CmdGetData",
  "CmdGetData",
  "RmakerLocalCtrl__CmdGetData",
  "rmaker_local_ctrl",
  sizeof(RmakerLocalCtrl__CmdGetData),
  4,
  rmaker_local_ctrl__cmd_get_data__field_descriptors,
  rmaker_local_ctrl__cmd_get_data__field_indices_by_name,
  1,  rmaker_local_ctrl__cmd_get_data__number_ranges,
  (ProtobufCMessageInit) rmaker_local_ctrl__cmd_get_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rmaker_local_ctrl__resp_get_data__field_descriptors[2] =
{
  {
    "Status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__RespGetData, status),
    &rmaker_local_ctrl__rmaker_local_ctrl_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Buf",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__RespGetData, buf),
    &rmaker_local_ctrl__payload_buf__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmaker_local_ctrl__resp_get_data__field_indices_by_name[] = {
  1,   /* field[1] = Buf */
  0,   /* field[0] = Status */
};
static const ProtobufCIntRange rmaker_local_ctrl__resp_get_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rmaker_local_ctrl__resp_get_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.RespGetData",
  "RespGetData",
  "RmakerLocalCtrl__RespGetData",
  "rmaker_local_ctrl",
  sizeof(RmakerLocalCtrl__RespGetData),
  2,
  rmaker_local_ctrl__resp_get_data__field_descriptors,
  rmaker_local_ctrl__resp_get_data__field_indices_by_name,
  1,  rmaker_local_ctrl__resp_get_data__number_ranges,
  (ProtobufCMessageInit) rmaker_local_ctrl__resp_get_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rmaker_local_ctrl__rmaker_local_ctrl_payload__field_descriptors[3] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RmakerLocalCtrl__RMakerLocalCtrlPayload, msg),
    &rmaker_local_ctrl__rmaker_local_ctrl_msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmdGetData",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RmakerLocalCtrl__RMakerLocalCtrlPayload, payload_case),
    offsetof(RmakerLocalCtrl__RMakerLocalCtrlPayload, cmdgetdata),
    &rmaker_local_ctrl__cmd_get_data__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "respGetData",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RmakerLocalCtrl__RMakerLocalCtrlPayload, payload_case),
    offsetof(RmakerLocalCtrl__RMakerLocalCtrlPayload, respgetdata),
    &rmaker_local_ctrl__resp_get_data__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmaker_local_ctrl__rmaker_local_ctrl_payload__field_indices_by_name[] = {
  1,   /* field[1] = cmdGetData */
  0,   /* field[0] = msg */
  2,   /* field[2] = respGetData */
};
static const ProtobufCIntRange rmaker_local_ctrl__rmaker_local_ctrl_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.RMakerLocalCtrlPayload",
  "RMakerLocalCtrlPayload",
  "RmakerLocalCtrl__RMakerLocalCtrlPayload",
  "rmaker_local_ctrl",
  sizeof(RmakerLocalCtrl__RMakerLocalCtrlPayload),
  3,
  rmaker_local_ctrl__rmaker_local_ctrl_payload__field_descriptors,
  rmaker_local_ctrl__rmaker_local_ctrl_payload__field_indices_by_name,
  2,  rmaker_local_ctrl__rmaker_local_ctrl_payload__number_ranges,
  (ProtobufCMessageInit) rmaker_local_ctrl__rmaker_local_ctrl_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rmaker_local_ctrl__rmaker_local_ctrl_status__enum_values_by_number[4] =
{
  { "Success", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Success", 0 },
  { "Fail", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Fail", 1 },
  { "InvalidParam", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__InvalidParam", 2 },
  { "NoMemory", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__NoMemory", 3 },
};
static const ProtobufCIntRange rmaker_local_ctrl__rmaker_local_ctrl_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex rmaker_local_ctrl__rmaker_local_ctrl_status__enum_values_by_name[4] =
{
  { "Fail", 1 },
  { "InvalidParam", 2 },
  { "NoMemory", 3 },
  { "Success", 0 },
};
const ProtobufCEnumDescriptor rmaker_local_ctrl__rmaker_local_ctrl_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.RMakerLocalCtrlStatus",
  "RMakerLocalCtrlStatus",
  "RmakerLocalCtrl__RMakerLocalCtrlStatus",
  "rmaker_local_ctrl",
  4,
  rmaker_local_ctrl__rmaker_local_ctrl_status__enum_values_by_number,
  4,
  rmaker_local_ctrl__rmaker_local_ctrl_status__enum_values_by_name,
  1,
  rmaker_local_ctrl__rmaker_local_ctrl_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue rmaker_local_ctrl__rmaker_local_ctrl_data_type__enum_values_by_number[2] =
{
  { "TypeParams", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeParams", 0 },
  { "TypeConfig", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeConfig", 1 },
};
static const ProtobufCIntRange rmaker_local_ctrl__rmaker_local_ctrl_data_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex rmaker_local_ctrl__rmaker_local_ctrl_data_type__enum_values_by_name[2] =
{
  { "TypeConfig", 1 },
  { "TypeParams", 0 },
};
const ProtobufCEnumDescriptor rmaker_local_ctrl__rmaker_local_ctrl_data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.RMakerLocalCtrlDataType",
  "RMakerLocalCtrlDataType",
  "RmakerLocalCtrl__RMakerLocalCtrlDataType",
  "rmaker_local_ctrl",
  2,
  rmaker_local_ctrl__rmaker_local_ctrl_data_type__enum_values_by_number,
  2,
  rmaker_local_ctrl__rmaker_local_ctrl_data_type__enum_values_by_name,
  1,
  rmaker_local_ctrl__rmaker_local_ctrl_data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue rmaker_local_ctrl__rmaker_local_ctrl_msg_type__enum_values_by_number[2] =
{
  { "TypeCmdGetData", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeCmdGetData", 0 },
  { "TypeRespGetData", "RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeRespGetData", 1 },
};
static const ProtobufCIntRange rmaker_local_ctrl__rmaker_local_ctrl_msg_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex rmaker_local_ctrl__rmaker_local_ctrl_msg_type__enum_values_by_name[2] =
{
  { "TypeCmdGetData", 0 },
  { "TypeRespGetData", 1 },
};
const ProtobufCEnumDescriptor rmaker_local_ctrl__rmaker_local_ctrl_msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rmaker_local_ctrl.RMakerLocalCtrlMsgType",
  "RMakerLocalCtrlMsgType",
  "RmakerLocalCtrl__RMakerLocalCtrlMsgType",
  "rmaker_local_ctrl",
  2,
  rmaker_local_ctrl__rmaker_local_ctrl_msg_type__enum_values_by_number,
  2,
  rmaker_local_ctrl__rmaker_local_ctrl_msg_type__enum_values_by_name,
  1,
  rmaker_local_ctrl__rmaker_local_ctrl_msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
