/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: local_ctrl.proto */

#ifndef PROTOBUF_C_local_5fctrl_2eproto__INCLUDED
#define PROTOBUF_C_local_5fctrl_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RmakerLocalCtrl__PayloadBuf RmakerLocalCtrl__PayloadBuf;
typedef struct RmakerLocalCtrl__CmdGetData RmakerLocalCtrl__CmdGetData;
typedef struct RmakerLocalCtrl__RespGetData RmakerLocalCtrl__RespGetData;
typedef struct RmakerLocalCtrl__RMakerLocalCtrlPayload RmakerLocalCtrl__RMakerLocalCtrlPayload;


/* --- enums --- */

typedef enum _RmakerLocalCtrl__RMakerLocalCtrlStatus {
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Success = 0,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Fail = 1,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__InvalidParam = 2,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__NoMemory = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS)
} RmakerLocalCtrl__RMakerLocalCtrlStatus;
typedef enum _RmakerLocalCtrl__RMakerLocalCtrlDataType {
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeParams = 0,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeConfig = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE)
} RmakerLocalCtrl__RMakerLocalCtrlDataType;
typedef enum _RmakerLocalCtrl__RMakerLocalCtrlMsgType {
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeCmdGetData = 0,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeRespGetData = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE)
} RmakerLocalCtrl__RMakerLocalCtrlMsgType;

/* --- messages --- */

struct  RmakerLocalCtrl__PayloadBuf
{
  ProtobufCMessage base;
  uint32_t offset;
  ProtobufCBinaryData payload;
  uint32_t totallen;
};
#define RMAKER_LOCAL_CTRL__PAYLOAD_BUF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_local_ctrl__payload_buf__descriptor) \
, 0, {0,NULL}, 0 }


/*
 * Command to get data (params or config) - contains offset to request next chunk 
 */
struct  RmakerLocalCtrl__CmdGetData
{
  ProtobufCMessage base;
  RmakerLocalCtrl__RMakerLocalCtrlDataType datatype;
  uint32_t offset;
  /*
   * Optional timestamp for signed response 
   */
  int64_t timestamp;
  /*
   * Flag to indicate if timestamp is provided (since 0 is a valid timestamp) 
   */
  protobuf_c_boolean hastimestamp;
};
#define RMAKER_LOCAL_CTRL__CMD_GET_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_local_ctrl__cmd_get_data__descriptor) \
, RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeParams, 0, 0, 0 }


/*
 * Response with data (params or config) 
 */
struct  RmakerLocalCtrl__RespGetData
{
  ProtobufCMessage base;
  RmakerLocalCtrl__RMakerLocalCtrlStatus status;
  RmakerLocalCtrl__PayloadBuf *buf;
};
#define RMAKER_LOCAL_CTRL__RESP_GET_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_local_ctrl__resp_get_data__descriptor) \
, RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Success, NULL }


typedef enum {
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__NOT_SET = 0,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD_CMD_GET_DATA = 10,
  RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD_RESP_GET_DATA = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__CASE)
} RmakerLocalCtrl__RMakerLocalCtrlPayload__PayloadCase;

struct  RmakerLocalCtrl__RMakerLocalCtrlPayload
{
  ProtobufCMessage base;
  RmakerLocalCtrl__RMakerLocalCtrlMsgType msg;
  RmakerLocalCtrl__RMakerLocalCtrlPayload__PayloadCase payload_case;
  union {
    RmakerLocalCtrl__CmdGetData *cmdgetdata;
    RmakerLocalCtrl__RespGetData *respgetdata;
  };
};
#define RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor) \
, RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeCmdGetData, RMAKER_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__NOT_SET, {0} }


/* RmakerLocalCtrl__PayloadBuf methods */
void   rmaker_local_ctrl__payload_buf__init
                     (RmakerLocalCtrl__PayloadBuf         *message);
size_t rmaker_local_ctrl__payload_buf__get_packed_size
                     (const RmakerLocalCtrl__PayloadBuf   *message);
size_t rmaker_local_ctrl__payload_buf__pack
                     (const RmakerLocalCtrl__PayloadBuf   *message,
                      uint8_t             *out);
size_t rmaker_local_ctrl__payload_buf__pack_to_buffer
                     (const RmakerLocalCtrl__PayloadBuf   *message,
                      ProtobufCBuffer     *buffer);
RmakerLocalCtrl__PayloadBuf *
       rmaker_local_ctrl__payload_buf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_local_ctrl__payload_buf__free_unpacked
                     (RmakerLocalCtrl__PayloadBuf *message,
                      ProtobufCAllocator *allocator);
/* RmakerLocalCtrl__CmdGetData methods */
void   rmaker_local_ctrl__cmd_get_data__init
                     (RmakerLocalCtrl__CmdGetData         *message);
size_t rmaker_local_ctrl__cmd_get_data__get_packed_size
                     (const RmakerLocalCtrl__CmdGetData   *message);
size_t rmaker_local_ctrl__cmd_get_data__pack
                     (const RmakerLocalCtrl__CmdGetData   *message,
                      uint8_t             *out);
size_t rmaker_local_ctrl__cmd_get_data__pack_to_buffer
                     (const RmakerLocalCtrl__CmdGetData   *message,
                      ProtobufCBuffer     *buffer);
RmakerLocalCtrl__CmdGetData *
       rmaker_local_ctrl__cmd_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_local_ctrl__cmd_get_data__free_unpacked
                     (RmakerLocalCtrl__CmdGetData *message,
                      ProtobufCAllocator *allocator);
/* RmakerLocalCtrl__RespGetData methods */
void   rmaker_local_ctrl__resp_get_data__init
                     (RmakerLocalCtrl__RespGetData         *message);
size_t rmaker_local_ctrl__resp_get_data__get_packed_size
                     (const RmakerLocalCtrl__RespGetData   *message);
size_t rmaker_local_ctrl__resp_get_data__pack
                     (const RmakerLocalCtrl__RespGetData   *message,
                      uint8_t             *out);
size_t rmaker_local_ctrl__resp_get_data__pack_to_buffer
                     (const RmakerLocalCtrl__RespGetData   *message,
                      ProtobufCBuffer     *buffer);
RmakerLocalCtrl__RespGetData *
       rmaker_local_ctrl__resp_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_local_ctrl__resp_get_data__free_unpacked
                     (RmakerLocalCtrl__RespGetData *message,
                      ProtobufCAllocator *allocator);
/* RmakerLocalCtrl__RMakerLocalCtrlPayload methods */
void   rmaker_local_ctrl__rmaker_local_ctrl_payload__init
                     (RmakerLocalCtrl__RMakerLocalCtrlPayload         *message);
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__get_packed_size
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload   *message);
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__pack
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload   *message,
                      uint8_t             *out);
size_t rmaker_local_ctrl__rmaker_local_ctrl_payload__pack_to_buffer
                     (const RmakerLocalCtrl__RMakerLocalCtrlPayload   *message,
                      ProtobufCBuffer     *buffer);
RmakerLocalCtrl__RMakerLocalCtrlPayload *
       rmaker_local_ctrl__rmaker_local_ctrl_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_local_ctrl__rmaker_local_ctrl_payload__free_unpacked
                     (RmakerLocalCtrl__RMakerLocalCtrlPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RmakerLocalCtrl__PayloadBuf_Closure)
                 (const RmakerLocalCtrl__PayloadBuf *message,
                  void *closure_data);
typedef void (*RmakerLocalCtrl__CmdGetData_Closure)
                 (const RmakerLocalCtrl__CmdGetData *message,
                  void *closure_data);
typedef void (*RmakerLocalCtrl__RespGetData_Closure)
                 (const RmakerLocalCtrl__RespGetData *message,
                  void *closure_data);
typedef void (*RmakerLocalCtrl__RMakerLocalCtrlPayload_Closure)
                 (const RmakerLocalCtrl__RMakerLocalCtrlPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    rmaker_local_ctrl__rmaker_local_ctrl_status__descriptor;
extern const ProtobufCEnumDescriptor    rmaker_local_ctrl__rmaker_local_ctrl_data_type__descriptor;
extern const ProtobufCEnumDescriptor    rmaker_local_ctrl__rmaker_local_ctrl_msg_type__descriptor;
extern const ProtobufCMessageDescriptor rmaker_local_ctrl__payload_buf__descriptor;
extern const ProtobufCMessageDescriptor rmaker_local_ctrl__cmd_get_data__descriptor;
extern const ProtobufCMessageDescriptor rmaker_local_ctrl__resp_get_data__descriptor;
extern const ProtobufCMessageDescriptor rmaker_local_ctrl__rmaker_local_ctrl_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_local_5fctrl_2eproto__INCLUDED */
