# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: def.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 32, 1, "", "def.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tdef.proto\x12\x0ermaker_ch_resp"\x1f\n\x0c\x43mdCRPayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c"1\n\rRespCRPayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0f\n\x07node_id\x18\x02 \x01(\t"\x15\n\x13\x43mdGetNodeIDPayload"\'\n\x14RespGetNodeIDPayload\x12\x0f\n\x07node_id\x18\x01 \x01(\t"\x1b\n\x19\x43mdDisableChalRespPayload"\x1c\n\x1aRespDisableChalRespPayload"\xbe\x04\n\x13RMakerChRespPayload\x12\x30\n\x03msg\x18\x01 \x01(\x0e\x32#.rmaker_ch_resp.RMakerChRespMsgType\x12\x32\n\x06status\x18\x02 \x01(\x0e\x32".rmaker_ch_resp.RMakerChRespStatus\x12\x43\n\x1b\x63mdChallengeResponsePayload\x18\n \x01(\x0b\x32\x1c.rmaker_ch_resp.CmdCRPayloadH\x00\x12\x45\n\x1crespChallengeResponsePayload\x18\x0b \x01(\x0b\x32\x1d.rmaker_ch_resp.RespCRPayloadH\x00\x12\x42\n\x13\x63mdGetNodeIDPayload\x18\x0c \x01(\x0b\x32#.rmaker_ch_resp.CmdGetNodeIDPayloadH\x00\x12\x44\n\x14respGetNodeIDPayload\x18\r \x01(\x0b\x32$.rmaker_ch_resp.RespGetNodeIDPayloadH\x00\x12N\n\x19\x63mdDisableChalRespPayload\x18\x0e \x01(\x0b\x32).rmaker_ch_resp.CmdDisableChalRespPayloadH\x00\x12P\n\x1arespDisableChalRespPayload\x18\x0f \x01(\x0b\x32*.rmaker_ch_resp.RespDisableChalRespPayloadH\x00\x42\t\n\x07payload*K\n\x12RMakerChRespStatus\x12\x0b\n\x07Success\x10\x00\x12\x08\n\x04\x46\x61il\x10\x01\x12\x10\n\x0cInvalidParam\x10\x02\x12\x0c\n\x08\x44isabled\x10\x03*\xb8\x01\n\x13RMakerChRespMsgType\x12\x1c\n\x18TypeCmdChallengeResponse\x10\x00\x12\x1d\n\x19TypeRespChallengeResponse\x10\x01\x12\x14\n\x10TypeCmdGetNodeID\x10\x02\x12\x15\n\x11TypeRespGetNodeID\x10\x03\x12\x1a\n\x16TypeCmdDisableChalResp\x10\x04\x12\x1b\n\x17TypeRespDisableChalResp\x10\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "def_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RMAKERCHRESPSTATUS"]._serialized_start = 813
    _globals["_RMAKERCHRESPSTATUS"]._serialized_end = 888
    _globals["_RMAKERCHRESPMSGTYPE"]._serialized_start = 891
    _globals["_RMAKERCHRESPMSGTYPE"]._serialized_end = 1075
    _globals["_CMDCRPAYLOAD"]._serialized_start = 29
    _globals["_CMDCRPAYLOAD"]._serialized_end = 60
    _globals["_RESPCRPAYLOAD"]._serialized_start = 62
    _globals["_RESPCRPAYLOAD"]._serialized_end = 111
    _globals["_CMDGETNODEIDPAYLOAD"]._serialized_start = 113
    _globals["_CMDGETNODEIDPAYLOAD"]._serialized_end = 134
    _globals["_RESPGETNODEIDPAYLOAD"]._serialized_start = 136
    _globals["_RESPGETNODEIDPAYLOAD"]._serialized_end = 175
    _globals["_CMDDISABLECHALRESPPAYLOAD"]._serialized_start = 177
    _globals["_CMDDISABLECHALRESPPAYLOAD"]._serialized_end = 204
    _globals["_RESPDISABLECHALRESPPAYLOAD"]._serialized_start = 206
    _globals["_RESPDISABLECHALRESPPAYLOAD"]._serialized_end = 234
    _globals["_RMAKERCHRESPPAYLOAD"]._serialized_start = 237
    _globals["_RMAKERCHRESPPAYLOAD"]._serialized_end = 811
# @@protoc_insertion_point(module_scope)
