# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: local_ctrl.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "local_ctrl.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10local_ctrl.proto\x12\x11rmaker_local_ctrl"?\n\nPayloadBuf\x12\x0e\n\x06Offset\x18\x01 \x01(\r\x12\x0f\n\x07Payload\x18\x02 \x01(\x0c\x12\x10\n\x08TotalLen\x18\x03 \x01(\r"\x83\x01\n\nCmdGetData\x12<\n\x08\x44\x61taType\x18\x01 \x01(\x0e\x32*.rmaker_local_ctrl.RMakerLocalCtrlDataType\x12\x0e\n\x06Offset\x18\x02 \x01(\r\x12\x11\n\tTimestamp\x18\x03 \x01(\x03\x12\x14\n\x0cHasTimestamp\x18\x04 \x01(\x08"s\n\x0bRespGetData\x12\x38\n\x06Status\x18\x01 \x01(\x0e\x32(.rmaker_local_ctrl.RMakerLocalCtrlStatus\x12*\n\x03\x42uf\x18\x02 \x01(\x0b\x32\x1d.rmaker_local_ctrl.PayloadBuf"\xc7\x01\n\x16RMakerLocalCtrlPayload\x12\x36\n\x03msg\x18\x01 \x01(\x0e\x32).rmaker_local_ctrl.RMakerLocalCtrlMsgType\x12\x33\n\ncmdGetData\x18\n \x01(\x0b\x32\x1d.rmaker_local_ctrl.CmdGetDataH\x00\x12\x35\n\x0brespGetData\x18\x0b \x01(\x0b\x32\x1e.rmaker_local_ctrl.RespGetDataH\x00\x42\t\n\x07payload*N\n\x15RMakerLocalCtrlStatus\x12\x0b\n\x07Success\x10\x00\x12\x08\n\x04\x46\x61il\x10\x01\x12\x10\n\x0cInvalidParam\x10\x02\x12\x0c\n\x08NoMemory\x10\x03*9\n\x17RMakerLocalCtrlDataType\x12\x0e\n\nTypeParams\x10\x00\x12\x0e\n\nTypeConfig\x10\x01*A\n\x16RMakerLocalCtrlMsgType\x12\x12\n\x0eTypeCmdGetData\x10\x00\x12\x13\n\x0fTypeRespGetData\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "local_ctrl_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RMAKERLOCALCTRLSTATUS"]._serialized_start = 557
    _globals["_RMAKERLOCALCTRLSTATUS"]._serialized_end = 635
    _globals["_RMAKERLOCALCTRLDATATYPE"]._serialized_start = 637
    _globals["_RMAKERLOCALCTRLDATATYPE"]._serialized_end = 694
    _globals["_RMAKERLOCALCTRLMSGTYPE"]._serialized_start = 696
    _globals["_RMAKERLOCALCTRLMSGTYPE"]._serialized_end = 761
    _globals["_PAYLOADBUF"]._serialized_start = 39
    _globals["_PAYLOADBUF"]._serialized_end = 102
    _globals["_CMDGETDATA"]._serialized_start = 105
    _globals["_CMDGETDATA"]._serialized_end = 236
    _globals["_RESPGETDATA"]._serialized_start = 238
    _globals["_RESPGETDATA"]._serialized_end = 353
    _globals["_RMAKERLOCALCTRLPAYLOAD"]._serialized_start = 356
    _globals["_RMAKERLOCALCTRLPAYLOAD"]._serialized_end = 555
# @@protoc_insertion_point(module_scope)
