/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file lwip.c
 * @brief LwIP socket mocks for the network.
 */

#include "socket_mocks.h"
#include <sys/socket.h>
#include <sys/types.h>
#include <errno.h>
#include <stddef.h>
#include <stdbool.h>

// Global Fault State
static volatile bool g_fail_traffic = false;

void socket_mock_force_failure(bool enable_fault)
{
    g_fail_traffic = enable_fault;
}

// Prototypes for the "Real" functions generated by the linker
extern int __real_lwip_connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen);
extern ssize_t __real_lwip_send(int sockfd, const void *buf, size_t len, int flags);
extern ssize_t __real_lwip_recv(int sockfd, void *buf, size_t len, int flags);

// --- CONNECT ---
int __wrap_lwip_connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen)
{
    if (g_fail_traffic) {
        errno = ETIMEDOUT; // Simulate unreachable server
        return -1;
    }
    return __real_lwip_connect(sockfd, addr, addrlen);
}

// --- SEND ---
ssize_t __wrap_lwip_send(int sockfd, const void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET; // Simulate broken pipe
        return -1;
    }
    return __real_lwip_send(sockfd, buf, len, flags);
}

// --- RECV ---
ssize_t __wrap_lwip_recv(int sockfd, void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET; // Simulate connection drop
        return -1;
    }
    return __real_lwip_recv(sockfd, buf, len, flags);
}
