/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file standard.c
 * @brief Standard socket mocks for the network.
 */

#include "socket_mocks.h"
#include <sys/socket.h>
#include <sys/types.h>
#include <errno.h>
#include <stddef.h>
#include <stdbool.h>

// Global Fault State
static volatile bool g_fail_traffic = false;

void socket_mock_force_failure(bool enable_fault)
{
    g_fail_traffic = enable_fault;
}

/**
 * -------------------------------------------------------------------------
 * STRATEGY A: GNU Linker Wrapping
 * Targets: ESP-IDF, Linux (GCC/Clang)
 * -------------------------------------------------------------------------
 */
#if defined(USE_LINKER_WRAP)

// Prototypes for the "Real" functions generated by the linker
extern int __real_connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen);
extern ssize_t __real_send(int sockfd, const void *buf, size_t len, int flags);
extern ssize_t __real_recv(int sockfd, void *buf, size_t len, int flags);

// --- CONNECT ---
int __wrap_connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen)
{
    if (g_fail_traffic) {
        errno = ETIMEDOUT; // Simulate unreachable server
        return -1;
    }
    return __real_connect(sockfd, addr, addrlen);
}

// --- SEND ---
ssize_t __wrap_send(int sockfd, const void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET; // Simulate broken pipe
        return -1;
    }
    return __real_send(sockfd, buf, len, flags);
}

// --- RECV ---
ssize_t __wrap_recv(int sockfd, void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET; // Simulate connection drop
        return -1;
    }
    return __real_recv(sockfd, buf, len, flags);
}

/*
 * -------------------------------------------------------------------------
 * STRATEGY B: Runtime Symbol Interposition (Shadowing)
 * Targets: macOS, BSD, generic POSIX without --wrap support
 * -------------------------------------------------------------------------
 */
#else

#define _GNU_SOURCE // Required for RTLD_NEXT on some Linux systems
#include <dlfcn.h> // For dlsym

// Function pointer types for the real OS functions
typedef int (*real_connect_fn)(int, const struct sockaddr *, socklen_t);
typedef ssize_t (*real_send_fn)(int, const void *, size_t, int);
typedef ssize_t (*real_recv_fn)(int, void *, size_t, int);

// --- CONNECT ---
int connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen)
{
    if (g_fail_traffic) {
        errno = ETIMEDOUT;
        return -1;
    }
    // Fetch standard function from next library in chain
    real_connect_fn real_conn = (real_connect_fn)dlsym(RTLD_NEXT, "connect");
    return real_conn(sockfd, addr, addrlen);
}

// --- SEND ---
ssize_t send(int sockfd, const void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET;
        return -1;
    }
    real_send_fn real_snd = (real_send_fn)dlsym(RTLD_NEXT, "send");
    return real_snd(sockfd, buf, len, flags);
}

// --- RECV ---
ssize_t recv(int sockfd, void *buf, size_t len, int flags)
{
    if (g_fail_traffic) {
        errno = ECONNRESET;
        return -1;
    }
    real_recv_fn real_rcv = (real_recv_fn)dlsym(RTLD_NEXT, "recv");
    return real_rcv(sockfd, buf, len, flags);
}
#endif
